obj-${CONFIG_VIDEO_ONSEMI_REGMAP}		+= onsemi-regmap.o
obj-${CONFIG_VIDEO_ONSEMI_CORE}			+= onsemi-core.o

obj-${CONFIG_VIDEO_ONSEMI_AR0144}		+= onsemi-ar0144.o

ccflags-${CONFIG_VIDEO_ONSEMI_ENABLE_DEBUG}	+= -DDEBUG
