/* SPDX-License-Identifier: GPL-2.0-or-later */

/*
 * Generic ONSemi ARxxx register descriptions
 *
 * Copyright (C) 2018 Enrico Scholz <enrico.scholz@sigma-chemnitz.de>
 */

#ifndef H_LINUX_MEDIA_I2C_ONSEMI_REG_H
#define H_LINUX_MEDIA_I2C_ONSEMI_REG_H

/* byte addressed alias for ONSEMI_FLD_RESET_REGISTER_STREAM bit */
#define ONSEMI_REG_MOD_SELECT			ONSEMI_REGMAP_8BIT_REG_TO_ADDR(0x301c)

/* byte addressed alias for ONSEMI_FLD_RESET_REGISTER_MASK_BAD bit */
#define ONSEMI_REG_MASK_CORRUPTED_FRAMES	ONSEMI_REGMAP_8BIT_REG_TO_ADDR(0x3023)

#define ONSEMI_REG_FRAME_STATUS			0x303c
#  define ONSEMI_FLD_FRAME_STATUS_STANDBY	BIT(1)

#define ONSEMI_REG_RESET_REGISTER		0x301a
#  define ONSEMI_FLD_RESET_REGISTER_PARAM_HOLD	BIT(15)
#  define ONSEMI_FLD_RESET_REGISTER_SMIA_DIS	BIT(12)
#  define ONSEMI_FLD_RESET_REGISTER_PLL_ON	BIT(11)
#  define ONSEMI_FLD_RESET_REGISTER_RESTART_BAD	BIT(10)
#  define ONSEMI_FLD_RESET_REGISTER_MASK_BAD	BIT(9)
#  define ONSEMI_FLD_RESET_REGISTER_GPI_EN	BIT(8)
#  define ONSEMI_FLD_RESET_REGISTER_PARALLEL_EN	BIT(7)
#  define ONSEMI_FLD_RESET_REGISTER_DRIVE_PINS	BIT(6)
#  define ONSEMI_FLD_RESET_REGISTER_LOCK_REG	BIT(3)
#  define ONSEMI_FLD_RESET_REGISTER_STREAM	BIT(2)


#endif	/* H_LINUX_MEDIA_I2C_ONSEMI_REG_H */
